import { FileLikeObject } from './file-like-object.class';
import { FileUploader } from './file-uploader.class';
export declare class FileItem {
    file: FileLikeObject;
    _file: File;
    alias: string;
    url: string;
    method: string;
    headers: any;
    withCredentials: boolean;
    formData: any;
    isReady: boolean;
    isUploading: boolean;
    isUploaded: boolean;
    isSuccess: boolean;
    isCancel: boolean;
    isError: boolean;
    progress: number;
    index: number;
    private _zone;
    private uploader;
    private some;
    private options;
    constructor(uploader: FileUploader, some: any, options: any);
    upload(): void;
    cancel(): void;
    remove(): void;
    onBeforeUpload(): void;
    onBuildForm(form: any): any;
    onProgress(progress: number): any;
    onSuccess(response: any, status: any, headers: any): any;
    onError(response: any, status: any, headers: any): any;
    onCancel(response: any, status: any, headers: any): any;
    onComplete(response: any, status: any, headers: any): any;
    _onBeforeUpload(): void;
    _onBuildForm(form: any): void;
    _onProgress(progress: number): void;
    _onSuccess(response: any, status: any, headers: any): void;
    _onError(response: any, status: any, headers: any): void;
    _onCancel(response: any, status: any, headers: any): void;
    _onComplete(response: any, status: any, headers: any): void;
    _prepareToUploading(): void;
}
